### ISSUE TITLE
Any plans to generate plain javascript files?

### ISSUE THREAD

**Issue by ralvs** [paljs/prisma-tools#115]
I'm trying to migrate a big project from prisma 1 to prisma 2.
Pal.js could help a lot, but I can't migrate the project to typescript right now. Its to much change

**Comment by AhmedElywa** [comment]
Yes current I working on JavaScript with two syntax es modules and normal Javascript

**Comment by ralvs** [comment]
Awesome! Thanks @AhmedElywa

**Comment by AhmedElywa** [comment]
Now we have support for JavaScript from v 1.3.2. You can use it by adding javascript property to the backend object in the pal.js file.

```js
module.exports = {
  backend: {
    generator: 'nexus-schema',
    onDelete: true,
    javaScript: true, // like this
  },
}

```
