### ISSUE TITLE
Possible to display/edit explicit many-to-many relations in Admin?

### ISSUE THREAD

**Issue by willwillis** [paljs/prisma-tools#117]
I have a few [explicit many-to-many relationships](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#explicit-many-to-many-relations) in my application, so that I can eventually store details about the relationship. Currently this doesn't seem supported in "Admin" is that correct? 

* 0 results are shown when viewing /admin/models/JobsOnSections

```
# simplified schema.prisma

model Dashboard {
    id        Int                    @id @default(autoincrement())
    name      String                 @unique
    sections  SectionsOnDashboards[]
}

model SectionsOnDashboards {
    dashboard   Dashboard @relation(fields: [dashboardId], references: [id])
    dashboardId Int
    section     Section   @relation(fields: [sectionId], references: [id])
    sectionId   Int
    order       Int?
    alias       String?
    @@id([sectionId, dashboardId])
}

model Section {
    id        Int      @id @default(autoincrement())
    name      String   @unique
    published Boolean  @default(false)
    dashboards SectionsOnDashboards[]
    jobs       JobsOnSections[]
}
```

Image 1) Dashboard => Sections => Section exists

![prisma-admin-playground](https://user-images.githubusercontent.com/46991/86680859-9d31c000-bfc4-11ea-9232-e7e6eef2059b.png)

Image 2) 0 rows displayed in Admin
![prisma-admin-1](https://user-images.githubusercontent.com/46991/86680850-9acf6600-bfc4-11ea-9cf9-4d4ab3f40b7d.png)

Could it be that the singular/plural form of Section/s can't be used on the same model?

Thanks.

**Comment by AhmedElywa** [comment]
Sorry @willwillis, until now any model did not have `@id`  in one field will be excluded from admin generated schema

**Comment by AhmedElywa** [comment]
will support many-to-many but this table will just have read and add you can't update or delete

**Comment by AhmedElywa** [comment]
with the new release v2.0.1, you can now list many-to-many relation table
