### ISSUE TITLE
Manually write schema.prisma is diffucult

### ISSUE THREAD

**Issue by adnanfuat** [paljs/prisma-tools#120]
**"after an update your `schema.prisma` run"**
https://prnt.sc/tkye8g

Is there a way easy way to update schema.prisma with my new database ?

Or I have to do only write manually? 
My database big. And write manually is diffucult

**Comment by AhmedElywa** [comment]
@adnanfuat yes if you have already existing DB you can use `prisma introspect` command to pull you DB into schema.prisma file but you need first to add your DB connection data into schema.prisma file 
All docs here https://www.prisma.io/docs/reference/tools-and-interfaces/introspection

If you DB is in Snake case like `first_name` and you want to convert into Camel case like `firstName` you can use my converter https://paljs.com/cli/schema#convert-to-camel-case

**Comment by AhmedElywa** [comment]
I will close this issue if you need any other thing please open a new one
