### ISSUE TITLE
Providing usable examples for paljs

### ISSUE THREAD

**Issue by martineboh** [paljs/prisma-tools#125]
Thanks for your work!

I find it really hard to use `prisma-tools` because enough example code isn't provided, just bunch of interfaces. I have been trying to generate SDL from my `schema.prisma` file for days now with no success using `pal g` command, even after creating pal.json in my root directory with schema.prisma in the prisma directory relative to root.

**Comment by AhmedElywa** [comment]
If you using pal.json you need to pass his name to `pal g` command like `pal g -c pal.json`  if you using `pal.js` so you can use `pal g` without any custom flags in the command 

Also, you not provided any errors message that sees what is wrong with you to help you

**Comment by martineboh** [comment]
Thanks for responding so quickly. It doesn't show any error, just displayed **Generating your files** in just a second. I am using `pal.js` with content:

```js
module.exports = {
    schemaFolder: '/prisma',
    backend: {
        models: ['Profile', 'Senator'],
        generator: 'sdl',
        onDelete: true,
        excludeQueriesAndMutations: ['aggregate']
    }
};
```
I ran `pal g` in the root directory - it generated src with the wrong Models: Course, Group, Post, Product, User...with their corresponding `typeDefs` and `resolvers.ts` that are not in my `schema.prisma` file

**Comment by AhmedElywa** [comment]
Talk to me in Prisma slack

**Comment by AhmedElywa** [comment]
So the problem you need to run `prisma generate` command first before `pal g` command
