### ISSUE TITLE
Question: Can the Paljs Table/Editor "Connect" many-to-many relations the way Prisma Studio does?

### ISSUE THREAD

**Issue by willwillis** [paljs/prisma-tools#130]
The Paljs admin/CRUD interface allows me to create new related objects, but I haven't found a way to connect 2 related items the way that Prisma Studio does, is that possible? Below a `Dashboard` has many `Groups` and from this screen I can associate multiple `Groups` to a `Dashboard` in one screen.

![image](https://user-images.githubusercontent.com/46991/93829738-ec86a480-fc33-11ea-997c-b6521e262f67.png)

**Comment by AhmedElywa** [comment]
Hi @willwillis, I already added this feature in [v1.2.3](https://github.com/paljs/prisma-tools/releases/tag/v1.2.3). Please do upgrade, and you can watch the release of the repo
