### ISSUE TITLE
The directive `@map` can not be used on relation fields

### ISSUE THREAD

**Issue by bkniffler** [paljs/prisma-tools#134]
I've just used `pal schema camel-case` and I got this error during my next `prisma generate` call:

<img width="530" alt="Bildschirmfoto 2020-09-30 um 08 22 02" src="https://user-images.githubusercontent.com/4349324/94655149-05f3b480-02f6-11eb-9bd5-73a2860c285d.png">

Is there a way to handle relations properly, in a way that prisma accepts?

**Comment by AhmedElywa** [comment]
Thanks for reporting this issue. I will skip the relation fields from this convert

**Comment by AhmedElywa** [comment]
@bkniffler can you please upgrade to v2.0.2 and test again?

**Comment by bkniffler** [comment]
I'm sorry, I was just evaluating prisma including paljs. I've now gotten rid of prisma, I'll not be able to try for now. But good job on fixing so fast :)

**Comment by jjangga0214** [comment]
@AhmedElywa Why don't you just change case without `@map`?

`@map` is not allowed to relation because the name of relation is not from database.
It's free and up to use to name it.

We do not need `@map`, but we just can name it camelcase.
