### ISSUE TITLE
How to do releases upgrade ?

### ISSUE THREAD

**Issue by sondh0127** [paljs/prisma-tools#137]
Did we have any approach to upgrade the current project?

I create a project with "@paljs/generator": "^2.3.1".
so how can I update to ^2.3.2 automatically or provide some way to resolve the conflict?

**Comment by AhmedElywa** [comment]
Hi @sondh0127, you always can look to releases notes [here](https://github.com/paljs/prisma-tools/releases) and see if there any breaking changes, or you can just update without any change in your code

Also, you can watch release notes. to get an email when any new release released
![image](https://user-images.githubusercontent.com/4535142/96221155-528fee80-0f8a-11eb-8b98-b68fd2310e17.png)

**Comment by sondh0127** [comment]
@AhmedElywa 
Thank you for your answer but this isn't what I mean. I would like to do that with paljs/cli instead. Something like:

1. npm install -g @paljs/cli
2. Go to the folder containing the old generated app
3. `pal c <the_old_foldername>` 

After that, I'll be able to see the diff of each file.

I ended up with the following step with the help of Vscode + Git

0. git commit `<old-app>`
1. `npm install -g @paljs/cli`
2. generate new app with `pal c <new-app>` 
3. drop all new file from `<new-app>` to `<old-app>` folder => choose `replace for all files`
4. revert unwanted changed

![Screen Capture_select-area_20201016155451](https://user-images.githubusercontent.com/62163604/96237991-25fac780-0fc8-11eb-9131-bf6476b48761.gif)

5. Generate with new cli
```shell
> pal g
> yarn generate
> yarn dev
```

Hope this help!

**Comment by AhmedElywa** [comment]
we don't make many changes in the examples files, but if you need to know what we change in these examples, there is an easier way to do this look to the new commit into [this folder](https://github.com/paljs/prisma-tools/tree/master/packages/create/examples) and see what we chnage
