### ISSUE TITLE
Add prettier for nexus generated files

### ISSUE THREAD

**Issue by sondh0127** [paljs/prisma-tools#138]
We should add `prettierConfig` in `makeSchema` function in order to get the risk of `husky` hooks and schema format problem

[https://nexusjs.org/docs/api/make-schema#prettierconfig](https://nexusjs.org/docs/api/make-schema#prettierconfig)
In `nexusSchema.ts`
```
prettierConfig: join(process.cwd(), '.prettierrc.js'),
```

**Comment by AhmedElywa** [comment]
Thanks for your activation here.
the easier way to add the nexus generated file to [.prettierignore](https://github.com/paljs/prisma-tools/blob/master/packages/create/examples/full-stack-nextjs/.prettierignore) file 

we have generated all files into the `src/generated` folder and for an issue with `next.js v9.5.5` we moved nexus generated file to root folder and forget to add this file into ignoring file will add in next release.
