### ISSUE TITLE
Support for passing a specific prisma client in plugins

### ISSUE THREAD

**Issue by roderickhodgson** [paljs/prisma-tools#139]
Hi Ahmed,

I notice the plugins import the `dmmf` from '@prisma/client'. This causes an issue when using a custom path for the generated prisma client. 

For example with this directive in the schema

```
generator client {
  provider = "prisma-client-js"
  output   = "../generated/database/client"
}
```

This is a likely scenario if building a GraphQL with multiple data sources, and therefore using more than one prisma client.

Would it be possible to support passing the client to the plugin?

Thanks!

**Comment by AhmedElywa** [comment]
@roderickhodgson, thanks for your issue. I am already working on that.

**Comment by AhmedElywa** [comment]
@roderickhodgson please update to last version https://github.com/paljs/prisma-tools/releases/tag/v2.5.0

**Comment by achintha-weerasinghe** [comment]
Hi, `dmmf` does not seem to be exported now or at least not the same way it did before. Anyhow, the generate client exports a Prisma object. Inside that object I found `dmmf` and `DMMF` both. But nothing works! Any solution for this?
