### ISSUE TITLE
Suggestion of Generator options

### ISSUE THREAD

**Issue by codingfunwoody** [paljs/prisma-tools#140]
Hi, can you add a option excludeFieldsAndQueriesAndMutationsByModel?

i just want to exclude some fields in some queries or mutations. E.g. exclude "id" field in mutations of update, remain "id" field in queries

**Comment by AhmedElywa** [comment]
I didn't get your idea. Can you please add an example of usage?

**Comment by codingfunwoody** [comment]
Sorry my unclear question,
My expectation is excluding "id" field in input types of mutation. E.g. create a user should not include "id" field in input type of mutation.
I think this is nexusjs problem, i will ask them later.
Thanks for your reply
