### ISSUE TITLE
Update peer dependencies to graphql 15

### ISSUE THREAD

**Issue by ZiiMakc** [paljs/prisma-tools#144]
When installing `npm i @paljs/plugins`

I get warning:
`npm WARN graphql-tag@2.10.3 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.`

As i can see graphql-tag support graphql 15: https://github.com/apollographql/graphql-tag/pull/299

Can graphql-tag be updated?

**Comment by AhmedElywa** [comment]
@ZiiMakc updated `graphql-tag` to the last version, and it uses `graphql` v15
