### ISSUE TITLE
PrismaTable edit row doesn't work when using uuid() instead of Int

### ISSUE THREAD

**Issue by chrisbull** [paljs/prisma-tools#158]
When using UUIDs for the id of the model, everything works fine. However, when you click on "edit" it using router.query to get the id, but it strips the `router.query` variable and only uses the first 5 digits of the UUID.

For example: `http://localhost:3000/admin/models/User?update=369062d2-119d-4be8-a471-b2bd81be74f9`
Will error because it tries to do a look up on `369062d2` instead of the full string.

**Comment by AhmedElywa** [comment]
Thanks for reporting.
Please try the latest version `2.6.3`
