### ISSUE TITLE
@paljs/cli v2.8.2 does not generate Prisma enums in resolversTypes.ts

### ISSUE THREAD

**Issue by ZenSoftware** [paljs/prisma-tools#159]
In the latest release of @paljs/cli v2.8.2, there seems to be a bug whereby Prisma enums are no longer generating their equivalent Typescript types within the **resolversTypes.ts** output.  This is causing compile issues as there are missing types.

**schema.prisma**
```gql
...

enum Pool {
  A
  B
}

enum Score {
  A
  B
  C
  D
}
```

I see in my git diff that within **resolversTypes.ts**, the follow lines have been removed from the output previously generated using @paljs/cli v2.6.3
```ts
export enum Pool {
  A = 'A',
  B = 'B',
}
export enum Score {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
}
```

When compiling my app the following errors occur:
```
ERROR in C:/a/Work/oss/apps/api/src/app/graphql/resolversTypes.ts(1824,10):
TS2304: Cannot find name 'Pool'.
ERROR in C:/a/Work/oss/apps/api/src/app/graphql/resolversTypes.ts(1825,11):
TS2304: Cannot find name 'Score'.
Version: typescript 4.0.3
```

**Comment by AhmedElywa** [comment]
Working on that now

**Comment by AhmedElywa** [comment]
Can you try the last version `2.8.3`?

**Comment by ZenSoftware** [comment]
Thanks @AhmedElywa, that fixed it. ^_^
