### ISSUE TITLE
 Error: Could not find query-engine binary.

### ISSUE THREAD

**Issue by afuyo** [paljs/prisma-tools#162]
Hi ,
I am trying to run the examples as described in the read.me When issuing 
`pal g`
I get following error: 
Error: Could not find query-engine binary. Searched in 
    /usr/lib/node_modules/@paljs/cli/node_modules/@prisma/sdk/query-engine-debian-openssl-1.1.x and 
    /usr/lib/node_modules/@paljs/cli/node_modules/@prisma/query-engine-debian-openssl-1.1.x

Best Regards
Artur

**Comment by AhmedElywa** [comment]
Please try the last version, `2.9.1`

**Comment by AhmedElywa** [comment]
I will close this issue. If you still face this issue with the last version, please comment here again.

**Comment by gaejoon-ahn** [comment]
same error message yet.

$ pal g
Prisma Schema loaded from server/prisma/schema.prisma
◢ Generating your files    Error: Could not find query-engine binary. Searched in 
    /usr/lib/node_modules/@paljs/cli/node_modules/@prisma/sdk/query-engine-debian-openssl-1.1.x and 
    /usr/lib/node_modules/@paljs/cli/node_modules/@prisma/query-engine-debian-openssl-1.1.x

$ pal -v
@paljs/cli/2.13.0 linux-x64 node-v12.20.2
