### ISSUE TITLE
Bug: SDL and resolver generation not consistent for findFirst queries

### ISSUE THREAD

**Issue by pakatagoh** [paljs/prisma-tools#166]
The image below shows the query generated by `pal g`. The generated query for an `Organisation` model has  `findFirstOrganisation`s return type is an array.
![image](https://user-images.githubusercontent.com/37908805/104119890-ab92d700-536d-11eb-8f9f-9685fa97aaa1.png)

It's not consistent with the return type of the `findFirstOrganisation` resolver.

Should the return type be `Organisation` instead of `[Organisation!]` ? 

See the return type for `findFirst` here: https://www.prisma.io/docs/concepts/components/prisma-client/crud#return-type-1

Currently using @paljs/cli and @paljs/plugins `v2.11.0`, prisma/client and @prisma/cli `v2.14.0`

**Comment by pakatagoh** [comment]
Potential fix in  #167

**Comment by AhmedElywa** [comment]
Fixed by @pakatagoh

**Comment by pakatagoh** [comment]
thanks! @AhmedElywa 

Do you know when you'll publish a new release with the changes?

**Comment by AhmedElywa** [comment]
Today, sorry for late.

**Comment by AhmedElywa** [comment]
V2.11.1 have your fix
