### ISSUE TITLE
Error generating nexus schema if model's name in lower case

### ISSUE THREAD

**Issue by carlosfiori** [paljs/prisma-tools#174]
Using the nexus generator, if the model name is in lowercase, the error below is occurs:
![image](https://user-images.githubusercontent.com/20682772/106504025-25b60780-64a5-11eb-9a22-1e8e585c2a54.png)
![image](https://user-images.githubusercontent.com/20682772/106504045-2e0e4280-64a5-11eb-8c77-d1ee7177c64f.png)

**Comment by AhmedElywa** [comment]
please try the last version, `2.12.0`  and give me your feedback
