### ISSUE TITLE
need to set default pageSize of PrismaTable

### ISSUE THREAD

**Issue by gtolarc** [paljs/prisma-tools#186]
https://github.com/paljs/prisma-tools/blob/master/packages/admin/src/PrismaTable/Table/index.tsx#L66

The setting to put pageSize in this part should be out. Can you add it to the props of PrismaTable? @AhmedElywa

**Comment by AhmedElywa** [comment]
you mean the options 
![image](https://user-images.githubusercontent.com/4535142/108225328-83ed1680-7144-11eb-83b3-d7fa65aa9f2c.png)

**Comment by gtolarc** [comment]
Yes, the default setting is 10, but I wish there was an option to change this.
