### ISSUE TITLE
problems when using menuItem using different queries in the same model

### ISSUE THREAD

**Issue by gtolarc** [paljs/prisma-tools#190]
I want to use the menu with the same model separated by query as follows.

```javascript
const menuItems: MenuItemType[] = {
      title: 'TITLE',
      children: [
        { title: 'SUB_TITLE1', link: { href: '/admin/models/Sample?status=0' } },
        { title: 'SUB_TITLE2', link: { href: '/admin/models/Sample?status=2' } },
      ],
    },
}
```

In this case, if you click each menu, the routing is fine, but there is a problem that the actual table is not filtered.
The cause seems to be that filterHandler is not automatically called according to query changes. Can you solve this problem? @AhmedElywa

**Comment by AhmedElywa** [comment]
We changed all the admin panel
