### ISSUE TITLE
Is it production-ready?

### ISSUE THREAD

**Issue by omar-dulaimi** [paljs/prisma-tools#193]
Hello,

Coming from Prisma 1 with prisma binding world, and currently in the upgrade process to Prisma 2.
I tested TypeGraphQL a little bit and so far I have decided that we won't be using it for production since it's going to generate a lot of breaking changes on our clients devices. Hence why I'm coming back to the SDL approach.

So my question, is this library production-ready? Any companies using it production?
Do they have any feedback about it?

I would appreciate it to find out more, before switching our backend project back to SDL and stopping the change to TypeGraphQL-prisma.

**Comment by AhmedElywa** [comment]
In the first, our library just a development helper tool, so you need it to generate the code instead of writing it by your hand 

Also, I am already using all these tools in two big projects in production now

**Comment by omar-dulaimi** [comment]
That's great to hear. Anywhere I could find examples with sample implemented resolvers?

**Comment by AhmedElywa** [comment]
You can use our [cli](https://paljs.com/#install-paljs-cli)to start a new project, and then you can put your prisma schema inside this example and create the resolvers

**Comment by omar-dulaimi** [comment]
Awesome!
