### ISSUE TITLE
How to deep filter

### ISSUE THREAD

**Issue by haleksandre** [paljs/prisma-tools#202]
How do you deep filter the returned select?

Prisma Models
```prisma
model User {
  id        String     @id @default(cuid())
  email     String
  profile   Profile?
}

model Profile {
  /// The id matching the user id
  id         String        @id
  user       User          @relation(fields: [id], references: [id])
  firstName  String
  lastName   String
}
```
GraphQL Query
```graphql
query Users {
  users {
    email
    profile {
      firstName
      lastName
      name
    }
  }
}
```
Resolvers
```ts
t.list.nonNull.field("users", {
  type: "User",
  resolve: async (_, args, ctx, info) => {
    const { select } = new PrismaSelect(info).value;

    return ctx.prisma.user.findMany({
      select,
    });
  }
});

// Select Returns
{
  select: {
    email: true,
    profile: { 
      select: { 
        firstName: true,
        lastName: true,
        name: true   // This return an error since it's not present in the model.
      } 
    }
  }
}
```

Is there a way to force `PrismaSelect` to filter out the whole `select` (deep nested select as well) of every fields that is not present in the Prisma's DMMF?

**Comment by AhmedElywa** [comment]
It's already filter any field not in the model 

Did you generate the prisma client in a custom path or it's in @prisma/client

**Comment by haleksandre** [comment]
It's in `@prisma/client`.

Could it be possible that these lines are the issue?

https://github.com/paljs/prisma-tools/blob/1abadc6f2ddfdcf1e14761993d986b5f57f95353/packages/plugins/src/select.ts#L78-L80

Shouldn't `dataModel` actually be `datamodel`?
