### ISSUE TITLE
Select plugins not converting _count from graphql info

### ISSUE THREAD

**Issue by lukadriel7** [paljs/prisma-tools#205]
hello, thanks for the great library.
I am currently using prisma 2.21.2 along with paljs 3.0.6. I have enabled the preview feature "selectRelationCount" but the select plugin doesn't seem to recognize the _count field from the graphql info parameter.

I am using nestjs and generating my graphql schema using prisma-nestjs-graphql library

**Comment by AhmedElywa** [comment]
Hi @lukadriel7, Thank you for your issue. I will work on this update ASAP

**Comment by lukadriel7** [comment]
@AhmedElywa Thank you very much

**Comment by AhmedElywa** [comment]
fixed in last version 3.2.0

**Comment by lukadriel7** [comment]
Sorry, but the @paljs/plugins npm version is still at 3.0.11

**Comment by AhmedElywa** [comment]
Sometimes it take some time to update see version https://www.npmjs.com/package/@paljs/plugins
