### ISSUE TITLE
[Feature Request] - Support for typegraphql generator instead of nexus.

### ISSUE THREAD

**Issue by Unbuttun** [paljs/prisma-tools#206]
Type Graphql do have a official generator for prisma already, so maybe it can be included in here if it's possible - [https://github.com/MichalLytek/typegraphql-prisma](https://github.com/MichalLytek/typegraphql-prisma)

**Comment by AhmedElywa** [comment]
Hi @Unbuttun, if the typegraphql have a generator already, what we will do 

Our job to build a generator for the graphql tools like nexus graphql-module and plain SDL first

So we do not have any job to do with typegraphql
