### ISSUE TITLE
PrismaSelect : Subscription Question : How to deal with mismatched payload shape

### ISSUE THREAD

**Issue by V-ed** [paljs/prisma-tools#211]
## Problem

Trying to implement subscriptions and based off [an example on another tool][example], I ran into an issue I can't seem to find any resource online that tackles the issue :

If the payload when creating an object is different than the request from the subscription's subfields, I do not receive all the data that the subscription asks for.

Example :

```graphql
mutation {
  addMessage(
    data: {
      text: "firstName is null :("
      user: { connect: { username: "V-ed" } }
    }
  ) {
    text
    time
    user {
      username
      # Notice how there is no `firstName` subfield above
    }
  }
}

subscription {
  messageAdded {
    text
    time
    user {
      username
      firstName
      # Notice how there is the `firstName` subfield above
    }
  }
}
```

These two queries work, as in the message specified gets added and the subscription does receive some data, but that latter point is the issue : it only receives the data that was asked in the `addMessage` mutation :

```json
{
  "data": {
    "messageAdded": {
      "text": "firstName is null :(",
      "time": "2021-05-17T21:56:11.823Z",
      "user": {
        "username": "V-ed",
        "firstName": null
      }
    }
  }
}
```

## Implementation

I'm using NestJS with Prisma, and here's my implementation (again, based off [an example on another tool][example]) :

```ts
	...
	@Mutation(() => Message, { nullable: true })
	async addMessage(@Args('data') data: MessageCreateInput, @Info() info: GraphQLResolveInfo) {
		const select = new PrismaSelect(info).value;

		const message = await this.prismaService.message.create({ data, ...select });

		this.pubSub.publish('messageAdded', { messageAdded: message });

		return message;
	}

	@Subscription(() => Message, { name: 'messageAdded' })
	subscribeMessageAdded() {
		return this.pubSub.asyncIterator('messageAdded');
	}
	...
```

## My understanding

Since `addMessage` function only selects the fields that the `info`'s GraphQLResolveInfo variable provides, the return of Prisma's select only contains what the initial request asked for :

```
text
time
user {
  username
  # Notice how there is no `firstName` subfield above
}
```

This makes Prisma's `message.create` only select the fields above, therefore does not contain `firstName`. Since the subscribe method asks for `firstName`, it is set to `null` because Prisma didn't select it (as PrismaSelect didn't include it, which is the excepted outcome).

## My Question

Is there any way in which we could deal with subscription's requests and, in this example, `addMessage`'s own GraphQLResolveInfo? In other words, can I gracefully ask all the data required for both `addMessage` and `subscribeMessageAdded`?

## My potential solution

One way I see it is that I could add the GraphQLResolveInfo of `subscribeMessageAdded` into a list which would take all the subscribed listeners and deep merge all the subscribers' GraphQLResolveInfo's selectors so that it might be more heavy for the database, but at least all the subscribers gets the data they requested for.

Here's an example I was thinking of :

<details>
<summary>(shrunken for length)</summary>

```ts
...
import merge from 'deepmerge'; // https://github.com/TehShrike/deepmerge

const dict: {
	[key: string]: never[];
} = {};

@Resolver(() => Message)
export class MessageResolver {
	
	...

	@Mutation(() => Message, { nullable: true })
	async addMessage(@Args('data') data: MessageCreateInput, @Info() info: GraphQLResolveInfo) {
		const select = new PrismaSelect(info).value;

		const allSelect = merge.all([select, ...dict['messageAdded']]);

		const message = await this.prismaService.message.create({ data, ...allSelect });

		this.pubSub.publish('messageAdded', { messageAdded: message });

		return message;
	}
	
	@Subscription(() => Message, { name: 'messageAdded' })
	subscribeMessageAdded(@Info() info: GraphQLResolveInfo) {
		const select = new PrismaSelect(info).value;

		dict['messageAdded'] = (dict['messageAdded'] ?? []).concat(select);

		return this.pubSub.asyncIterator('messageAdded');
	}
}
```

</details>

While this seems to work (haven't tested a lot of more complex use cases), it is cumbersome to add this sort of contraption to every subscription that I will make... Yes, I could make a more generic approach to adding the selectors of the `subscribeMessageAdded` to the array of `messageAdded` event dict, but this is still a lot of work, and doesn't even cover when clients unsubscribes.

Is there any other way to make this work?

[example]: https://github.com/unlight/prisma-nestjs-graphql/blob/a39b0cd1dc60b0dbd2c5fd653e7459a2c9676f95/src/example/user/user.resolver.ts#L51-L54

**Comment by V-ed** [comment]
For the record, I was able to make my current 'workaround' / potential solution using a more generic approach, as shown below (_**NestJS**_) :

<details>
<summary>pub-sub.ts</summary>

```ts
import { Injectable } from '@nestjs/common';
import { PrismaSelect } from '@paljs/plugins';
import deepmerge from 'deepmerge';
import { GraphQLResolveInfo } from 'graphql';
import { PubSub as PubSubGraphQL } from 'graphql-subscriptions';

export function withCancel<T>(asyncIterator: AsyncIterator<T | undefined>, onCancel: () => void): AsyncIterator<T | undefined> {
	if (!asyncIterator.return) {
		asyncIterator.return = () => Promise.resolve({ value: undefined, done: true });
	}

	const savedReturn = asyncIterator.return.bind(asyncIterator);

	asyncIterator.return = () => {
		onCancel();
		return savedReturn();
	};

	return asyncIterator;
}

type AsyncIteratorParamType = Parameters<PubSubGraphQL['asyncIterator']>[0];
type PublishParamType = Parameters<PubSubGraphQL['publish']>[0];

type PrismaSelector = Record<string, unknown>;

@Injectable()
export class PubSub extends PubSubGraphQL {
	eventSubsSelectors: Record<string, unknown[]> = {};

	prismaSubscribe(triggers: AsyncIteratorParamType, info: GraphQLResolveInfo) {
		const sub = this.asyncIterator(triggers);

		const select = new PrismaSelect(info).value;
		const fullTriggers = Array.isArray(triggers) ? triggers : [triggers];

		fullTriggers.forEach((trigger) => (this.eventSubsSelectors[trigger] = (this.eventSubsSelectors[trigger] ?? []).concat(select)));

		return withCancel(sub, () => {
			fullTriggers.forEach((trigger) => {
				this.eventSubsSelectors[trigger] = this.eventSubsSelectors[trigger].filter((selector) => selector != select);

				if (!this.eventSubsSelectors[trigger].length) {
					delete this.eventSubsSelectors[trigger];
				}
			});
		});
	}

	async prismaMutate<T>(triggerName: PublishParamType, info: GraphQLResolveInfo, creator: (allSelect: PrismaSelector) => PromiseLike<T>) {
		const select = new PrismaSelect(info).value;

		const subscriberSelects = this.eventSubsSelectors[triggerName];

		const allSelect: PrismaSelector = subscriberSelects ? deepmerge.all([select, ...subscriberSelects]) : select;

		const returnValue = await creator(allSelect);

		await this.publish(triggerName, { [triggerName]: returnValue });

		return returnValue;
	}
}
```

</details>

<details>
<summary>message.resolver.ts</summary>

```ts
import { PrismaService } from '$/prisma.service';
import { PubSub } from '$/pub-sub';
import { Message, MessageCreateInput, MessageUpdateWithWhereUniqueWithoutUserInput, MessageWhereInput } from '$prisma-graphql/message';
import { Args, Info, Mutation, Query, Resolver, Subscription } from '@nestjs/graphql';
import { PrismaSelect } from '@paljs/plugins';
import { GraphQLResolveInfo } from 'graphql';

@Resolver(() => Message)
export class MessageResolver {
	constructor(private prismaService: PrismaService, private pubSub: PubSub) {}
	...

	@Mutation(() => Message, { nullable: true })
	async addMessage(@Args('data') data: MessageCreateInput, @Info() info: GraphQLResolveInfo) {
		const message = await this.pubSub.prismaMutate('messageAdded', info, (allSelect) => {
			return this.prismaService.message.create({ data, ...allSelect });
		});

		return message;
	}

	@Subscription(() => Message, { name: 'messageAdded' })
	subscribeMessageAdded(@Info() info: GraphQLResolveInfo) {
		return this.pubSub.prismaSubscribe('messageAdded', info);
	}
}

```

</details>

**Comment by AhmedElywa** [comment]
Look like a big issue will read and back to you

**Comment by V-ed** [comment]
Sure! Although I would remove the `bug` tag as it isn't really a bug, more like a question on how to integrate PrismaSelect with subscriptions...

**Comment by AhmedElywa** [comment]
What I get for you is to select id when adding a new message and fetch new data for subscription 

```ts
...
	@Mutation(() => Message, { nullable: true })
	async addMessage(@Args('data') data: MessageCreateInput, @Info() info: GraphQLResolveInfo) {
// add default fields  get it even if frontEnd not requested it 
//const defaultFields = {
//  User: { firstName: true },
//};
// or request id to fetch all data in subscription level
const defaultFields = {
  User: { id: true },
};
		const select = new PrismaSelect(info, {defaultFields}).value;

		const message = await this.prismaService.message.create({ data, ...select });

		this.pubSub.publish('messageAdded', { messageAdded: message });

		return message;
	}

	@Subscription(() => Message, { name: 'messageAdded' })
	subscribeMessageAdded(@Info() info: GraphQLResolveInfo) {
              const select = new PrismaSelect(info).value;
	      const {id} =  this.pubSub.asyncIterator('messageAdded');
              return this.prismaService.message.findUnique({ where: {id}, ...select });
	}
	...
	```

**Comment by V-ed** [comment]
So forcing the id in the create function and using said id for the pubsub's async iterator... Interesting, will try it out and report back here!

**Comment by V-ed** [comment]
Unfortunately, the async iterator does not return the ID of the object (the AsyncIterator nodejs object only returns an iterator basically), so this does not work... I don't really know how the async iterator object works in node js, so maybe there's a way to tweak your way to work by creating another async iterator, but I haven't looked enough into that yet.

![image](https://user-images.githubusercontent.com/16652915/123490502-31d06c00-d5e2-11eb-8fd3-365b17eeb26d.png)

**Comment by AhmedElywa** [comment]
You can add async and try 
```ts

async subscribeMessageAdded(@Info() info: GraphQLResolveInfo) {
    const select = new PrismaSelect(info).value;
    const { id } = await this.pubSub.asyncIterator('messageAdded');
    return await this.prismaService.message.findUnique({ where: { id }, ...select });
  }

```

**Comment by V-ed** [comment]
> You can add async and try
> 
> ```ts
> async subscribeMessageAdded(@Info() info: GraphQLResolveInfo) {
>     const select = new PrismaSelect(info).value;
>     const { id } = await this.pubSub.asyncIterator('messageAdded');
>     return await this.prismaService.message.findUnique({ where: { id }, ...select });
>   }
> ```

unfortunately no, AsyncIterator is not a `PromiseLike` object (there's no `then` to the object)

**Comment by V-ed** [comment]
I think I might use [this instead](https://docs.nestjs.com/graphql/subscriptions#mutating-subscription-payloads) : by mutating the result of the payload, I get the id like you tried to do then would do another query to get the proper object

**Comment by AhmedElywa** [comment]
I think you can do my idea with any way but I don't know how nestjs work

**Comment by V-ed** [comment]
> I think you can do my idea with any way but I don't know how nestjs work 

Just for the record, even though I'm using NestJS, this applies to using [the graphql-subscriptions package](https://www.npmjs.com/package/graphql-subscriptions) (this is where the AsyncIterator comes from) and there are opened issues currently about not being able to use an async function for mutating, which makes your proposed solution impossible to do with that package (instead of returning the JSON object, it would return the promise, which frontend obviously can't parse)

maybe NestJS accepts other kinds of objects for subscriptions (aka other packages), I'll look into that, but so far my own solution still holds up, despite its flaws

I'll update with what I find here!

**Comment by V-ed** [comment]
Actually, nevermind my previous message, with the [Custom AsyncIterator Wrappers](https://github.com/apollographql/graphql-subscriptions#custom-asynciterator-wrappers) method, we can successfully fetch the data with a given id like you initially wanted to do - I even made a small test in my codebase, I'm tweaking it some more and will add it here once done.

However, this made me realize something - I am now not sure what is the best approach to this issue. Hear me out :

By selecting all the data required when mutating, this allows the subscribers to *not* do another query to the database with their own imperative query size.
This means that with your solution, if there are 10 subscribers with each their own queries, the database will be queried 10 times with a different set of data, EVERY time that a mutation happens with that handler attached.

While with my original method, the fields are calculated in advance and the database is only queried once, and even then it really isn't being queried, as it's the `prisma.model.create` function that returns all the data (so it's on creation rather than querying).

Your method is interesting if there are only 1 subscriber as it makes the resulting query map directly to what the subscriber expects and what the mutator expects too, and even there you access the database twice or more (1 when creating + _n_ for each _n_ subscriber).

I think I'll stick to my method for now as I think that accessing the database the least amount of times possible is the better solution (_what if the database state changes mid queries?_), but that means some more processing power upfront (I'm basically offloading the process from database querying to node object merging).

**Comment by AhmedElywa** [comment]
what I see is you make your mutation request the same as the subscription request will be best for performance
