### ISSUE TITLE
Changelog for v3

### ISSUE THREAD

**Issue by ahollenbach** [paljs/prisma-tools#213]
Howdy! Do you have a changelog for v3? Just curious what the breaking changes are before I uptake the version. Thanks!

**Comment by AhmedElywa** [comment]
Working on that now; I just no had free time to do this.
most of the changes were in admin and cli packages

**Comment by ahollenbach** [comment]
Awesome, thank you!

**Comment by AhmedElywa** [comment]
Thanks for waiting 
https://github.com/paljs/prisma-tools/releases/tag/v3.0.0

**Comment by ahollenbach** [comment]
Thank you! Much appreciated.
