### ISSUE TITLE
Question: Transform output of M:M relationship

### ISSUE THREAD

**Issue by rryter** [paljs/prisma-tools#215]
Hello :-)

I'm currently trying to achieve the following:

**schema.prisma**
```
model Post {
  tags Tag[]
}

model Tag {
  name String @unique
  posts Post[]
}
```

This generates the correct DB tables and queries (`pal g`).

But now I would like to be able receive `tags` as an array of strings, and **not** objects. I would like to be able to query it like this:

```
Post{
      tags
    }
```

I would like to avoid the following:
```
Post{
   tags{
     name
   }
}
```

Is this even possible? I was thinking I should just be able to add a `.map` in the resolver but it does not seem to be as simple as that. 

Thank you very much.

**Comment by AhmedElywa** [comment]
Yes, you can.
First, you need to exclude the generated type
Add this config to your `pal.js` file 

```js
module.exports = {
  backend: {
    generator: 'nexus',
    onDelete: true,
    excludeFieldsByModel: {Post: ['tags']}
  },
};
```

then add your custom type and export and add to exported nexus types

```js
const PostCustom = extendType({
  type: 'Post',
  definition(t) {
    t.list.string('tags', {
      resolve(parent as any) {
      // parent type will not have tags so we add as any because select plugin add it
        return parent.tags.map(tag => tag.name)
      },
    })
  },
})
```

**Comment by rryter** [comment]
Thank you very much for the fast feedback. 👍
