### ISSUE TITLE
Error: DateTime was already defined and imported as a type, check the docs for extending types

### ISSUE THREAD

**Issue by btodorce** [paljs/prisma-tools#220]
Not sure is this related to prisma-tools autogenerating prisma scalars or its cause of prisma.
Current stack is graphql nexus, prisma 2. Apollo server + using prisma-tools to generate crud for a set number of db tables. Trying to extend/overwrite overwrite the default DateTime, to handle cases like non RFC 3339 dates and custom date types with one DateTime scalar. But each time the scalar is added as a type to makeSchema this error is being thrown.

Question is if this isnt a bug can we exclude certain scalar not being generated so we can extend replace them with our own implementation.

**Comment by AhmedElywa** [comment]
I will add an option to be able to remove the default scalar

**Comment by btodorce** [comment]
Ty! Much appreciated

**Comment by btodorce** [comment]
any eta on this, we have a fairly large problem cause of this. We are using it to generate part of our crud, and the default datetime scalar serializes it as UTC while we need it in a specific time zone.

**Comment by AhmedElywa** [comment]
Sorry for the delay. I was busy last week. I will give it done time today or tomorrow

**Comment by AhmedElywa** [comment]
you can add now `excludeScalar` option with an array of excluded scalar `excludeScalar?: ('Json' | 'Decimal' | 'BigInt' | 'DateTime')[];`

**Comment by heygema** [comment]
howdy @AhmedElywa where to put the `excludeScalar` option?
