### ISSUE TITLE
SDL First Json error

### ISSUE THREAD

**Issue by DregondRahl** [paljs/prisma-tools#222]
I'm getting this error when i start the service "yarn dev" when my table has a json field with postgres db. Is it an apollo types issue?

```
model Setting {
    id               Int          @id @default(autoincrement())
    lotExpires       Boolean      @default(true)
    lotDisablePeriod Int?         @default(5) 
    lotNotification  Json?
}
```

![image](https://user-images.githubusercontent.com/749080/123514009-f1d6bb00-d6ad-11eb-8571-d963842133f3.png)

![image](https://user-images.githubusercontent.com/749080/123514133-f354b300-d6ae-11eb-88e5-9872f09d5395.png)

**Comment by AhmedElywa** [comment]
You need to add a Json scalar type to your GraphQL resolver https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/

**Comment by DregondRahl** [comment]
Thanks!
