### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by dannysofftie** [paljs/prisma-tools#228]
Hi team, this is an amazing tool that works really well with relational databases. Does `prisma.onDelete` support MongoDB? If so, an example will be great.

**Comment by AhmedElywa** [comment]
Hi @dannysofftie, 
we need to let you know that on Delete plugin dropped since Prisma now support onDelete 
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions#cascade

**Comment by dannysofftie** [comment]
Hi @AhmedElywa, Prisma currently supports `onDelete` on relational databases behind `referentialActions` flag. At the moment, MongoDB is not fully supported. Any thoughts on this?

**Comment by AhmedElywa** [comment]
Sorry, I have no experience with MongoDB

**Comment by dannysofftie** [comment]
No worries, much appreciated :+1:
