### ISSUE TITLE
Question about creating own queries and there resolvers

### ISSUE THREAD

**Issue by Hxgxn** [paljs/prisma-tools#242]
Hello,

at first I want to say, that your package is really awesome. It makes so many things so easy. But I have a question is it possible to put own queries "next to" the generated ones? For example I want to create a logic into one resolver instead of just findFirst or findUnique. Is this possible?

Greetings
Hagen

**Comment by AhmedElywa** [comment]
Hi @Hxgxn, 
Sorry for the delay. You can do that if you using the `nexus` generator if you use the `SDL` first generator you can't you must add new file with your custom logic
