### ISSUE TITLE
generate script throws error

### ISSUE THREAD

**Issue by rdmchr** [paljs/prisma-tools#248]
When running the generate script I get the following error:
```
PS D:\Projects\satorupal> npm run generate

> satorupal@0.0.2 generate
> pal g && npm run generate:prisma && npm run generate:nexus && npm run codegen


> satorupal@0.0.2 generate:prisma
> prisma generate                

Environment variables loaded from prisma\.env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (3.7.0 | library) to .\node_modules\@prisma\client in 102ms  
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
                                                                                    
import { PrismaClient } from '@prisma/client'                                          
const prisma = new PrismaClient()                                                      
                                                                                    

> satorupal@0.0.2 generate:nexus                         
> npm run ts-node --transpile-only src/server/nexusSchema


> satorupal@0.0.2 ts-node                                                                               
> ts-node -r tsconfig-paths/register --compiler-options '{"module":"CommonJS"}' "src/server/nexusSchema"

undefined:1        
'{module:CommonJS}'
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at parse (D:\Projects\satorupal\node_modules\ts-node\dist\util.js:51:45)
    at arg (D:\Projects\satorupal\node_modules\ts-node\node_modules\arg\index.js:122:24)
    at main (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:18:67)
    at Object.<anonymous> (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:351:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```
I also had to install `prisma` and `@prisma/client`, since those were not installed for some reason. Is my installation broken or what went wrong here?
Furthermore, do I find it strange, that the pal.js file opens when I run the `npm run generate` command since that does not happen when I just run `pal g`...
The template I chose was the Next.js full-stack one and the CSS framework I selected was only TailwindCSS. I also chose not to set up that multi schema thing.

**Comment by AhmedElywa** [comment]
the issue is because you are working on windows we pass this option to the ts-node command `'{"module":"CommonJS"}'` 
it's working correctly on my side MacOS, 
sorry I don't have any windows PC to check and fix 

look at this line in the `package.json` file `"ts-node": "ts-node -r tsconfig-paths/register --compiler-options '{\"module\":\"CommonJS\"}'",`

**Comment by joaoflaviosantos** [comment]
> Ao executar o script de geração, recebo o seguinte erro:
> 
> ```
> PS D:\Projects\satorupal> npm run generate
> 
> > satorupal@0.0.2 generate
> > pal g && npm run generate:prisma && npm run generate:nexus && npm run codegen
> 
> 
> > satorupal@0.0.2 generate:prisma
> > prisma generate                
> 
> Environment variables loaded from prisma\.env
> Prisma schema loaded from prisma\schema.prisma
> 
> ✔ Generated Prisma Client (3.7.0 | library) to .\node_modules\@prisma\client in 102ms  
> You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
>                                                                                     
> import { PrismaClient } from '@prisma/client'                                          
> const prisma = new PrismaClient()                                                      
>                                                                                     
> 
> > satorupal@0.0.2 generate:nexus                         
> > npm run ts-node --transpile-only src/server/nexusSchema
> 
> 
> > satorupal@0.0.2 ts-node                                                                               
> > ts-node -r tsconfig-paths/register --compiler-options '{"module":"CommonJS"}' "src/server/nexusSchema"
> 
> undefined:1        
> '{module:CommonJS}'
> ^
> 
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at parse (D:\Projects\satorupal\node_modules\ts-node\dist\util.js:51:45)
>     at arg (D:\Projects\satorupal\node_modules\ts-node\node_modules\arg\index.js:122:24)
>     at main (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:18:67)
>     at Object.<anonymous> (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:351:5)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> ```
> 
> Também tive que instalar e, já que não foram instaladas por algum motivo. Minha instalação está quebrada ou o que deu errado aqui? Além disso, eu acho estranho, que o arquivo .js amigo abre quando eu executar o comando já que isso não acontece quando eu apenas corro... O modelo que escolhi foi o Next.js full-stack e a estrutura CSS que selecionei era apenas TailwindCSS. Eu também escolhi não configurar essa coisa multi esquema.`prisma``@prisma/client``npm run generate``pal g`

Use this

```
{\\\"module\\\":\\\"commonjs\\\"}
```

**Comment by joaoflaviosantos** [comment]
> When running the generate script I get the following error:
> 
> ```
> PS D:\Projects\satorupal> npm run generate
> 
> > satorupal@0.0.2 generate
> > pal g && npm run generate:prisma && npm run generate:nexus && npm run codegen
> 
> 
> > satorupal@0.0.2 generate:prisma
> > prisma generate                
> 
> Environment variables loaded from prisma\.env
> Prisma schema loaded from prisma\schema.prisma
> 
> ✔ Generated Prisma Client (3.7.0 | library) to .\node_modules\@prisma\client in 102ms  
> You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
>                                                                                     
> import { PrismaClient } from '@prisma/client'                                          
> const prisma = new PrismaClient()                                                      
>                                                                                     
> 
> > satorupal@0.0.2 generate:nexus                         
> > npm run ts-node --transpile-only src/server/nexusSchema
> 
> 
> > satorupal@0.0.2 ts-node                                                                               
> > ts-node -r tsconfig-paths/register --compiler-options '{"module":"CommonJS"}' "src/server/nexusSchema"
> 
> undefined:1        
> '{module:CommonJS}'
> ^
> 
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at parse (D:\Projects\satorupal\node_modules\ts-node\dist\util.js:51:45)
>     at arg (D:\Projects\satorupal\node_modules\ts-node\node_modules\arg\index.js:122:24)
>     at main (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:18:67)
>     at Object.<anonymous> (D:\Projects\satorupal\node_modules\ts-node\dist\bin.js:351:5)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> ```
> 
> I also had to install and , since those were not installed for some reason. Is my installation broken or what went wrong here? Furthermore, do I find it strange, that the pal.js file opens when I run the command since that does not happen when I just run ... The template I chose was the Next.js full-stack one and the CSS framework I selected was only TailwindCSS. I also chose not to set up that multi schema thing.`prisma``@prisma/client``npm run generate``pal g`

Use this:

```
{\\\"module\\\":\\\"commonjs\\\"}
```

https://github.com/TypeStrong/ts-node/issues/992#issuecomment-605117906

**Comment by AhmedElywa** [comment]
Create a new file, `tsconfig-nexus.json` 

```json
{
  "compilerOptions": {
    "module": "CommonJS"
  },
  "extends": "./tsconfig.json"
}
```

`package.json`

```diff 
{
  "scripts": {
-   "ts-node": "ts-node -r tsconfig-paths/register --compiler-options '{\"module\":\"CommonJS\"}'",
+   "ts-node": "ts-node -r tsconfig-paths/register -P tsconfig-nexus.json"
  }
}
```

**Comment by rdmchr** [comment]
I no longer use GraphQL, so this issue no longer applies to me.
Feel free to close the issue if a fix is available.
