### ISSUE TITLE
Simple one-to-many apollo SDL first code generation not working

### ISSUE THREAD

**Issue by ZenSoftware** [paljs/prisma-tools#252]
Hello @AhmedElywa! 🎎

Pal.js apollo SDL first code generation does not seem to be working with a very simple _one-to-many_ schema.  I have created [a bare minimum reproduction](https://github.com/ZenSoftware/pal-repro) of this Pal.js bug for you by cloning your [prisma-tools/packages/create/examples/apollo-sdl-first](https://github.com/paljs/prisma-tools/tree/main/packages/create/examples/apollo-sdl-first) example and modifying the `schema.prisma` file.

**My system:**
- Windows 10
- Node v16.13.2
- prisma@3.8.1
- @paljs/plugins@4.0.13
- @paljs/cli@4.0.13

[schema.prisma](https://github.com/ZenSoftware/pal-repro/blob/03c7f2721e725ae20961f040b68c146dc87c8ece/prisma/schema.prisma#L10-L22)
```gql
 model User { 
   id        Int      @id @default(autoincrement()) 
   username  String   @unique 
   password  String 
  
   products Product[] 
 } 
  
 model Product { 
   id      Int  @id @default(autoincrement()) 
   owner   User @relation(fields: [ownerId], references: [id]) 
   ownerId Int 
 } 
```

Notice how the definition for `ProductUpdateManyMutationInput` is not being generated.
[src/resolversTypes.ts#L482-L485](https://github.com/ZenSoftware/pal-repro/blob/63cddd8b32324f2a83b658f27b65bf52137fccde/src/resolversTypes.ts#L482-L485)
```ts
/*
export interface ProductUpdateManyMutationInput {
   ... missing ...
}
*/

export interface UpdateManyProductArgs { 
   data: ProductUpdateManyMutationInput 
   where?: ProductWhereInput 
 }
```

Though `UserUpdateManyMutationInput` is being properly generated.

[resolversTypes.ts#L454-L457](https://github.com/ZenSoftware/pal-repro/blob/4f95f7c65f19f12e027887dbaa2e3e8bf8d388e2/src/resolversTypes.ts#L454-L457)
```ts
export interface UpdateManyUserArgs {
  data: UserUpdateManyMutationInput
  where?: UserWhereInput
}
```
[src/resolversTypes.ts#L605-L608](https://github.com/ZenSoftware/pal-repro/blob/63cddd8b32324f2a83b658f27b65bf52137fccde/src/resolversTypes.ts#L605-L608)
```ts
 export interface UserUpdateManyMutationInput { 
   username?: StringFieldUpdateOperationsInput 
   password?: StringFieldUpdateOperationsInput 
 } 
```

Would you happen to know what is happening?  Thanks 🎐

**Comment by f8k8** [comment]
It seems like this is still an issue. I've put together a minimal reproduction here: https://github.com/f8k8/paljs-bug. Clone it and do `npm install` then `npm run generate`. In the generated `resolversTypes.ts`, the `HouseUpdateManyMutationInput` is missing.

**Comment by f8k8** [comment]
I've figured out why this is happening. If the model (House in the case of the repo I linked) doesn't have any other fields, just an ID and relations, then the `XXXUpdateManyMutationInput` interface isn't generated. Presumably because it would have no fields.

**Comment by AhmedElywa** [comment]
this should fix now
