### ISSUE TITLE
@paljs/cli doesn't work at all on Windows

### ISSUE THREAD

**Issue by Atlinx** [paljs/prisma-tools#261]
When I run pal using `npx pal`, I get a blank line and the CLI exits. The workaround I've been using is WSL, however, WSL is very slow in accessing files from Windows drives (ie. `C:\\`), making the CLI slow as well.

**Comment by Atlinx** [comment]
It looks like the problem was having the config file named `pal.js`. I've renamed it to `pal.config.js`, and I've used `npx pal generate --config=pal.config.js` to run the generator.

**Comment by AhmedElywa** [comment]
Yes good catch I will change the default config file to be `pal.config.js`
