### ISSUE TITLE
@paljs/nexus : NEXUS__UNKNOWN__TYPE was already defined when updating to prisma 4.0.0

### ISSUE THREAD

**Issue by mohammed-bahumaish** [paljs/prisma-tools#273]
I'm using nexus plugin for input types in a nexus Graphql server. 
but when updating to Prisma 4 I got this error ` NEXUS__UNKNOWN__TYPE   was already defined when` .
when rolling back to Prisma 3.5 it works fine.

**Comment by AhmedElywa** [comment]
I am working on that now to update prisma version to prisma 4 and fix all breaking changes

**Comment by MitchellMonaghan** [comment]
Is there any progress update on this?

**Comment by simonjoom** [comment]
need to use the last prisma 3.15
because the one used by paljs 3.16 for node 14 seems buggy

**Comment by amitozalvo** [comment]
I was able to fix this issue by manually generating DMMF when the app starts
`import { getDMMF, getSchema } from '@prisma/internals';`
`const dmmf = await getDMMF({ datamodel: await getSchema() })`

And providing the DMMF to the paljs plugin when calling `makeSchema`
`
  plugins: [paljs({ dmmf: [dmmf] })]
`

**Comment by AhmedElywa** [comment]
This issue request is in #284
