### ISSUE TITLE
Update dependencies please

### ISSUE THREAD

**Issue by icazemier** [paljs/prisma-tools#274]
Please update your dependencies in @paljs/cli 🙏🏻 

It is depending on a **_deprecated_** `@prisma/sdk` which in turns uses an **_outdated_** `temp-write`: 

```
% npm ls uuid
/our_project
├─┬ @paljs/cli@4.1.0
│ └─┬ @prisma/sdk@3.15.2
│   ├─┬ checkpoint-client@1.1.21
│   │ └── uuid@8.3.2 deduped
│   └─┬ temp-write@4.0.0
│     └── uuid@3.4.0
```

**Comment by AhmedElywa** [comment]
I am working on that now to update prisma version to prisma 4 and fix all breaking changes

**Comment by mikaelkaron** [comment]
Any updates on this?

**Comment by yograf** [comment]
> I am working on that now to update prisma version to prisma 4 and fix all breaking changes

@AhmedElywa thanks for this great lib, can you share your prisma 4 code. I'll try to help and create PR to move it forward.

**Comment by AhmedElywa** [comment]
This issue request is in #284
