### ISSUE TITLE
Is there any recommended way to customize the PrismaTable CSS?

### ISSUE THREAD

**Issue by Fatezhang** [paljs/prisma-tools#276]
Hey!

I like the CURD feature very much, https://prisma-admin.paljs.com/admin. And I'm going to build my project which will have similar pages with `prisma admin`. I'd like to use `PrismaTable` so that I don't need to build the same wheels.

But I can't find any good way to customize PrismaTable, is there any document I missed, or PrismaTable doesn't support doing this?

And also, is it possible to customize the GraphQL query and mutation, since my schema generated in the backend contains a namespace like `namespace_findManyPosts`?

**Comment by AhmedElywa** [comment]
You can find the docs here https://paljs.com/prisma-admin

and you can't customize the query names for now

**Comment by Fatezhang** [comment]
Awesome thanks @AhmedElywa, I think I should find other ways to achieve this.

BTW, may I suggest `prisma tool` supports multi data sources? For DB1 and DB2 both have table `user`, maybe it's better to add some identification on the query name？
