### ISSUE TITLE
PrismaDelete doesn't remove same model relations

### ISSUE THREAD

**Issue by whekin** [paljs/prisma-tools#279]
Let's say I want to have specialPosts along with posts in the User model (from the pal js example schema), like this: 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/39103584/189717771-db33343b-0078-4c76-8487-24444bf0a320.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/39103584/189717938-26e1d818-dcd6-4da1-965e-a45a8f6f8ffb.png">

I set `/// @onDelete(CASCADE)` on both posts and specialPosts. But apparently only posts get removed. After analysing prisma queries, it turns out the onDelete executes the same delete query twice (removing posts with author, not specialAuthor & author).

I checked out the original onDelete source code, and it seems that it finds the first field that references the parent model. Thus, it won't ever reach other relations on the same parent model.

Maybe it's possible to get relation name (if exists) and find the field taking it into account? In case if that's not possible I think the docs should say about it

Thanks

**Comment by AhmedElywa** [comment]
Hi @whekin, We dropped this class a long time ago because Prisma support this now https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions#types-of-referential-actions

**Comment by whekin** [comment]
@AhmedElywa Thank you for reply! It makes sense. I think paljs.com docs should mention it though

**Comment by AhmedElywa** [comment]
This issue request is in #284
