### ISSUE TITLE
sdlInputs not working because of changes in prisma.

### ISSUE THREAD

**Issue by joaquimnetocel** [paljs/prisma-tools#283]
The "sdlInputs.ts" is not working because of changes in prisma 4.

As pointed [here](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4#prisma-no-longer-exports-prismadmmfschema-into-the-generated-prisma-client), Prisma no longer exports Prisma.dmmf.schema into the generated Prisma Client. 

I don't know if it helps, but the new getDMMF function can be imported with:

import { getDMMF } from "@prisma/internals/dist/engine-commands";

I thought about making a pull request, but as getDMMF is an asynchronous function, I don't know the best way to solve the problem.

**Comment by AhmedElywa** [comment]
This issue request is in #284
