### ISSUE TITLE
DeleteOneArgs where field should not be nullable

### ISSUE THREAD

**Issue by ZenSoftware** [paljs/prisma-tools#292]
Hi @AhmedElywa,

Pal.js SDL generation is producing arguments for `DeleteOne...Args` with a nullable `where` field for the TypeScript interfaces being generated.  Prisma requires the `where` field for all single deletes.  This is causing me some small issues when using TypeScript with `"strictNullChecks": true`.  I thought you should know.  Cheers 🥂

```ts
export interface DeleteOneUserArgs {
  where: UserWhereUniqueInput | null;
}
```
should be
```ts
export interface DeleteOneUserArgs {
  where: UserWhereUniqueInput;
}
```

**Comment by AhmedElywa** [comment]
Fixes in this pull request #309
