### ISSUE TITLE
`__typename` not returned in select

### ISSUE THREAD

**Issue by baptistemarchand** [paljs/prisma-tools#299]
Hi,

I have a query that looks like this :
```gql
user() {
    id
    firstname
    __typename
}
```

But when I do `new PrismaSelect(info).value` in my resolver, the result is `{ select: { id: true, firstname: true } }`.
Why is `__typename` not returned?

Thank you in advance for your help.

**Comment by AhmedElywa** [comment]
Hi

because the __typename is not in your prisma model and it's added by default from the graphql server

**Comment by baptistemarchand** [comment]
Thank you for your very quick answer!
In my case I had added a `__typename` field to all models with the help of a prisma client extension (don't ask..), that's why I was expecting the field to show up. But anyway, I solved my issue. Sorry for the noise.

Not related to `__typename`, but in case it can help someone stumbling on this issue : if you have a typo in your `schema.prisma`, the field won't be returned in the `select` and you won't get any errors.
