### ISSUE TITLE
TypeError: The "to" argument must be of type string. Received an instance of Object. Code: `ERR_INVALID_ARG_TYPE`

### ISSUE THREAD

**Issue by eunchurn** [paljs/prisma-tools#332]
## Steps of reproduce

1. Installation by using `@paljs/cli create`

```sh
npx @paljs/cli create
```
![image](https://github.com/paljs/prisma-tools/assets/7800413/f41aac54-fc4f-4696-8432-0b03a0069672)

```sh
yarn install
```

2. Generating

<img width="715" alt="image" src="https://github.com/paljs/prisma-tools/assets/7800413/033c5cda-3faa-4f42-9be2-ef55fe522f0a">

```
yarn run v1.22.22
$ pal g && npm -s run generate:prisma && npm -s run generate:nexus
    TypeError: The "to" argument must be of type string. Received an instance of Object
    Code: ERR_INVALID_ARG_TYPE
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What did I do wrong?

Tested Node Versions: v22.2.0, v20.13.1

**Comment by eunchurn** [comment]
https://github.com/paljs/prisma-tools/blob/39ea091ee8e0cd4d0014de1e7cbbd7a7cd41313e/packages/cli/src/commands/generate.ts#L67

I think there is no schema item defined in the `flags` value in `pal.config.js`. This issue occurs even if the flag is not given, due to the absence of the `schema` item. It seems there have been some changes in `@oclif/core`.

**Comment by AhmedElywa** [comment]
Fixed in the last version, We upgraded the Prisma version to 5.14
