### ISSUE TITLE
@prisma/internals >= 5.15.0 missing getSchemaPath - breaks utils package

### ISSUE THREAD

**Issue by jacobclarke92** [paljs/prisma-tools#334]
Just a heads up since they added multi-file schema support it looks like the `getSchemaPath` function isn't exported from @prisma/internals anymore.

Was getting this error before I realised what was going on, and eventually traced it back to the utils package.
```
    TypeError: (0 , internals_1.getSchemaPath) is not a function
```

Oddly enough after I downgraded all prisma packages to 5.14.0 (and explicitly installed the internals package to devDeps),  
I ended getting a different error message:
```
    TypeError: The "to" argument must be of type string. Received an instance of Object
    Code: ERR_INVALID_ARG_TYPE
```
I kind of suspect pnpm store shenanigans but am honestly not too sure.
Anyway it's still a breaking change that'll need to be updated somehow, am just in the middle of wrapping up a work week but might come have a look later if you want assistance?

**Comment by eunchurn** [comment]
When using version 5.14, pnpm installs @prisma/internal version 5.9. Therefore, in my case, fixing the @prisma/internal version as shown below resolved the error. In version 5.15, the same error occurs in paljs 7.0.0.

```json
{
  "pnpm": {
    "overrides": {
      "@prisma/internals": "5.14.0"
    }
  }
}
```

**Comment by AhmedElywa** [comment]
Please use the prisma 5.16 and paljs 7.0.1 and will fix that for you
