### ISSUE TITLE
createManyAndReturn types not what Pal.js is expecting

### ISSUE THREAD

**Issue by ZenSoftware** [paljs/prisma-tools#335]
Hi @AhmedElywa ! 🎐

I just wanted to let you know how my upgrade experience has been going for the new `createManyAndReturn` feature Prisma released.  I've been running into some small issues.

The actual type being generated by Prisma is some kind of super convoluted type for the new `createManyAndReturn` feature:
![paljs-debugging-2](https://github.com/paljs/prisma-tools/assets/14055877/862a2edb-5ead-4343-a6e5-56de1579409a)

You seem to be expecting the return type for the above to be exported as a declared TypeScript type named `CreateManyUserAndReturnOutputType`.  This type is not being generated for me utilizing `@prisma ^5.14.0`
![paljs-debugging-1](https://github.com/paljs/prisma-tools/assets/14055877/1e1ecccb-4c7e-4c99-9ef3-903170b39696)

- Here is a link to my [schema.prisma](https://github.com/ZenSoftware/zen/blob/base/apps/api/prisma/schema.prisma) file.
- Here is a link to my [resolversTypes.ts](https://github.com/ZenSoftware/zen/blob/base/apps/api/src/app/graphql/resolversTypes.ts) generated by Pal.js CLI.  As of today, it is generated via `@paljs/cli v6.0.7`.  I have been blocking my update to `@paljs/cli v7.0.0` until I can get this resolved.
 
Is this type that you are expecting being generated for you?

Thanks a million for your continual maintenance of Pal.js bud.  I would not have been able to create my [starter kit](https://github.com/zensoftware/zen) without your work. 🥂

**Comment by AhmedElywa** [comment]
With this new API from Prisma, we add a lot of work on the last version to support it.
Prisma changed the dmmf schema a lot to meet this new API so if you have any issues with this API update paljs to the last version and try it.

**Comment by ZenSoftware** [comment]
Yes, I am utilizing `@paljs/cli v7.0.0`.

The issue is the type `CreateManyUserAndReturnOutputType` does not exist within the TypeScript type definition file for my Prisma client.  The output for your generation for 'SDL first' is expecting this type within your `resolversTypes.ts` file that is generated. 乁(ツ)∫

```ts
// This type that you are expecting is missing within my Prisma client's index.d.ts file
Client.Prisma.CreateManyUserAndReturnOutputType

// Modifying my Prisma client's index.d.ts file fixes the problem and I can compile by manually adding this under the Prisma namespace
export type CreateManyUserAndReturnOutputType = Prisma.PrismaPromise<$Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, 'createManyAndReturn'>>;
```

**Comment by f8k8** [comment]
I'm seeing the same error. It looks like maybe the generator should create something like this instead:
```id?: Resolver<ReturnType<Client.Prisma.UserDelegate["createManyAndReturn"]>, {}, string>;```
